services:

  # =========================
  # Next.js
  # =========================
  app:
    build:
      # ホスト側のNext.jsプロジェクト
      context: ./frontend

      # frontendディレクトリ内のDockerfileを使用
      dockerfile: Dockerfile

    # Next.jsコンテナ名
    container_name: react-next-app

    # コンテナが終了した場合、自動的に再起動する
    # Docker自体を停止した場合は再起動しない
    restart: unless-stopped

    ports:
      # ホスト:コンテナ
      - "3000:3000"

    volumes:
      # =================================
      # Next.jsソースコード
      # =================================
      # ホスト: ScheduleTool/frontend
      # コンテナ: /app
      #
      # コンテナ内では /app がNext.jsプロジェクトのルートになる
      - ./frontend:/app

      # =================================
      # 設定ファイル
      # =================================
      # ホストの設定ファイルを
      # コンテナの /config/setting.json として読み取り専用でマウント
      - ./config/setting.json:/config/setting.json:ro

    environment:
      # =================================
      # Next.js
      # =================================
      WATCHPACK_POLLING: "true"

      # =================================
      # PostgreSQL
      # =================================
      # コンテナ間通信なのでホスト名は「db」
      DATABASE_URL: postgresql://momo:yuki@db:5432/schedule_db

    depends_on:
      - db


  # =========================
  # PostgreSQL
  # =========================
  db:
    image: postgres:17

    # PostgreSQLコンテナ名
    container_name: react-postgres

    # コンテナが終了した場合、自動的に再起動する
    restart: unless-stopped

    ports:
      # ホスト:コンテナ
      - "5432:5432"

    environment:
      # PostgreSQLユーザー
      POSTGRES_USER: momo

      # PostgreSQLパスワード
      POSTGRES_PASSWORD: yuki

      # PostgreSQLデータベース
      POSTGRES_DB: schedule_db

    volumes:
      # PostgreSQLのデータを永続化
      - postgres_data:/var/lib/postgresql/data


# =========================
# Docker Volumes
# =========================
volumes:
  postgres_data:
    external: true
    name: react-oracle_postgres_data
