services:

  # =========================
  # Next.js
  # =========================
  app:
    build:
      context: ./app
      dockerfile: Dockerfile

    container_name: react-next-app

    ports:
      - "3000:3000"

    volumes:
    # ホスト:コンテナ:ro →ro はRead Onry
      # ホストのソースコードをコンテナへマウント
      - ./app:/app
      # 設定ファイルをコンテナへマウント
      - ./config/setting.json:/config/setting.json:ro

      # node_modulesはDocker側で管理
      - node_modules:/app/node_modules

    environment:
      # Next.js
      WATCHPACK_POLLING: "true"

      # PostgreSQL接続情報
      DATABASE_URL: postgresql://postgres:postgres@db:5432/schedule_db

    depends_on:
      - db

  # =========================
  # PostgreSQL
  # =========================
  db:
    image: postgres:17

    container_name: react-postgres

    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: schedule_db

    volumes:
      # PostgreSQLのデータを保存
      - postgres_data:/var/lib/postgresql/data

# =========================
# Docker Volumes
# =========================
volumes:

  # Node.jsの依存パッケージ
  node_modules:

  # PostgreSQLのデータ
  postgres_data:
